services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: home_library
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/src/app/src
      - ./doc:/usr/src/app/doc
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
    ports:
      - '${PORT}:${PORT}'
    networks:
      - hl_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: hl-postgres-db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - hl_network

volumes:
  postgres_data:
  postgres_logs:

networks:
  hl_network:
    driver: bridge
